# Generated by Django 4.2.11 on 2024-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('hall_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'halls',
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id_allocine', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, max_length=10, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('pivot_genres', models.TextField(blank=True, max_length=1000, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=5000, null=True)),
                ('nationality', models.TextField(blank=True, max_length=255, null=True)),
                ('distributor', models.TextField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('pivot_director', models.TextField(blank=True, max_length=1000, null=True)),
                ('pivot_casting', models.TextField(blank=True, max_length=1000, null=True)),
                ('public_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('press_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('audience', models.CharField(blank=True, max_length=255, null=True)),
                ('societies', models.TextField(blank=True, max_length=255, null=True)),
                ('copies', models.IntegerField(blank=True, null=True)),
                ('pred_entries', models.IntegerField(blank=True, null=True)),
                ('true_entries', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies_w0',
            },
        ),
        migrations.CreateModel(
            name='MoviesHistory',
            fields=[
                ('id_allocine', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, max_length=10, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('pivot_genres', models.TextField(blank=True, max_length=1000, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=5000, null=True)),
                ('nationality', models.TextField(blank=True, max_length=255, null=True)),
                ('distributor', models.TextField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('pivot_director', models.TextField(blank=True, max_length=1000, null=True)),
                ('pivot_casting', models.TextField(blank=True, max_length=1000, null=True)),
                ('public_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('press_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('audience', models.CharField(blank=True, max_length=255, null=True)),
                ('societies', models.TextField(blank=True, max_length=255, null=True)),
                ('copies', models.IntegerField(blank=True, null=True)),
                ('pred_entries', models.IntegerField(blank=True, null=True)),
                ('true_entries', models.IntegerField(blank=True, null=True)),
                ('history_date', models.DateField(blank=True, max_length=10, null=True)),
                ('fixed_costs', models.IntegerField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies_history',
            },
        ),
        migrations.CreateModel(
            name='MoviesW1',
            fields=[
                ('id_allocine', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateField(blank=True, max_length=10, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('pivot_genres', models.TextField(blank=True, max_length=1000, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=5000, null=True)),
                ('nationality', models.TextField(blank=True, max_length=255, null=True)),
                ('distributor', models.TextField(blank=True, max_length=255, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('pivot_director', models.TextField(blank=True, max_length=1000, null=True)),
                ('pivot_casting', models.TextField(blank=True, max_length=1000, null=True)),
                ('public_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('press_rating', models.FloatField(blank=True, max_length=4, null=True)),
                ('audience', models.CharField(blank=True, max_length=255, null=True)),
                ('societies', models.TextField(blank=True, max_length=255, null=True)),
                ('copies', models.IntegerField(blank=True, null=True)),
                ('pred_entries', models.IntegerField(blank=True, null=True)),
                ('true_entries', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies_w1',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
